/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.GraphicsConfiguration;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author Braian
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {

        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icon.png")).getImage());
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Menu Principal");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUno = new javax.swing.JPanel();
        btnCrearAeropuertos = new javax.swing.JButton();
        btnCrearAeropuertos1 = new javax.swing.JButton();
        btnCrearAeropuertos2 = new javax.swing.JButton();
        btnCrearAeropuertos3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlUno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Aeropuerto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 14))); // NOI18N

        btnCrearAeropuertos.setFont(new java.awt.Font("Elected Office", 0, 18)); // NOI18N
        btnCrearAeropuertos.setText("Crear Aeropuerto");
        btnCrearAeropuertos.setPreferredSize(new java.awt.Dimension(204, 29));
        btnCrearAeropuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAeropuertosActionPerformed(evt);
            }
        });

        btnCrearAeropuertos1.setFont(new java.awt.Font("Elected Office", 0, 18)); // NOI18N
        btnCrearAeropuertos1.setText("Crear Vuelo");
        btnCrearAeropuertos1.setPreferredSize(new java.awt.Dimension(204, 29));
        btnCrearAeropuertos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAeropuertos1ActionPerformed(evt);
            }
        });

        btnCrearAeropuertos2.setFont(new java.awt.Font("Elected Office", 0, 18)); // NOI18N
        btnCrearAeropuertos2.setText("Cambiar Estado");
        btnCrearAeropuertos2.setPreferredSize(new java.awt.Dimension(204, 29));
        btnCrearAeropuertos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAeropuertos2ActionPerformed(evt);
            }
        });

        btnCrearAeropuertos3.setFont(new java.awt.Font("Elected Office", 0, 18)); // NOI18N
        btnCrearAeropuertos3.setText("Modificar Vuelo");
        btnCrearAeropuertos3.setPreferredSize(new java.awt.Dimension(204, 29));
        btnCrearAeropuertos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAeropuertos3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUnoLayout = new javax.swing.GroupLayout(pnlUno);
        pnlUno.setLayout(pnlUnoLayout);
        pnlUnoLayout.setHorizontalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUnoLayout.createSequentialGroup()
                        .addComponent(btnCrearAeropuertos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearAeropuertos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUnoLayout.createSequentialGroup()
                        .addComponent(btnCrearAeropuertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearAeropuertos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlUnoLayout.setVerticalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearAeropuertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearAeropuertos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearAeropuertos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearAeropuertos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUno.getAccessibleContext().setAccessibleName("MENU DE USUARIO");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearAeropuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAeropuertosActionPerformed
        CrearAeropuerto menu = new CrearAeropuerto();
        menu.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearAeropuertosActionPerformed

    private void btnCrearAeropuertos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAeropuertos1ActionPerformed
   CrearVuelo menu = new CrearVuelo();
        menu.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearAeropuertos1ActionPerformed

    private void btnCrearAeropuertos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAeropuertos2ActionPerformed
        EliminarVuelo menu = new EliminarVuelo();
        menu.setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearAeropuertos2ActionPerformed

    private void btnCrearAeropuertos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAeropuertos3ActionPerformed
        EditarVuelo menu = new EditarVuelo();
        menu.setVisible(true);
        this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearAeropuertos3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearAeropuertos;
    private javax.swing.JButton btnCrearAeropuertos1;
    private javax.swing.JButton btnCrearAeropuertos2;
    private javax.swing.JButton btnCrearAeropuertos3;
    private javax.swing.JPanel pnlUno;
    // End of variables declaration//GEN-END:variables
}
