/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.GraphicsConfiguration;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author Braian
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {

        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icon.png")).getImage());
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Menu Principal");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUno = new javax.swing.JPanel();
        btnRptUsuarios = new javax.swing.JButton();
        btnRptUsuarios1 = new javax.swing.JButton();
        btnRptUsuarios2 = new javax.swing.JButton();
        btnRptUsuarios3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlUno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Aeropuerto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 14))); // NOI18N

        btnRptUsuarios.setFont(new java.awt.Font("Elected Office", 0, 18)); // NOI18N
        btnRptUsuarios.setText("Reporte de Usuarios");
        btnRptUsuarios.setPreferredSize(new java.awt.Dimension(204, 29));
        btnRptUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRptUsuariosActionPerformed(evt);
            }
        });

        btnRptUsuarios1.setFont(new java.awt.Font("Elected Office", 0, 18)); // NOI18N
        btnRptUsuarios1.setText("Reporte de Vuelos");
        btnRptUsuarios1.setPreferredSize(new java.awt.Dimension(204, 29));
        btnRptUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRptUsuarios1ActionPerformed(evt);
            }
        });

        btnRptUsuarios2.setFont(new java.awt.Font("Elected Office", 0, 18)); // NOI18N
        btnRptUsuarios2.setText("Reporte de Aeropuertos");
        btnRptUsuarios2.setPreferredSize(new java.awt.Dimension(204, 29));
        btnRptUsuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRptUsuarios2ActionPerformed(evt);
            }
        });

        btnRptUsuarios3.setFont(new java.awt.Font("Elected Office", 0, 18)); // NOI18N
        btnRptUsuarios3.setLabel("Reporte Completo");
        btnRptUsuarios3.setPreferredSize(new java.awt.Dimension(204, 29));
        btnRptUsuarios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRptUsuarios3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUnoLayout = new javax.swing.GroupLayout(pnlUno);
        pnlUno.setLayout(pnlUnoLayout);
        pnlUnoLayout.setHorizontalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUnoLayout.createSequentialGroup()
                        .addComponent(btnRptUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRptUsuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUnoLayout.createSequentialGroup()
                        .addComponent(btnRptUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRptUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlUnoLayout.setVerticalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRptUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRptUsuarios2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRptUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRptUsuarios3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUno.getAccessibleContext().setAccessibleName("MENU DE USUARIO");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRptUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRptUsuariosActionPerformed
        reporteUsuarios menu = new reporteUsuarios();
        menu.setVisible(true);
        this.setVisible(false);
       // TODO add your handling code here:
    }//GEN-LAST:event_btnRptUsuariosActionPerformed

    private void btnRptUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRptUsuarios1ActionPerformed
        reporteAeropuerto menu = new reporteAeropuerto();
        menu.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRptUsuarios1ActionPerformed

    private void btnRptUsuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRptUsuarios2ActionPerformed
        reporteVuelo menu = new reporteVuelo();
        menu.setVisible(true);
        this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_btnRptUsuarios2ActionPerformed

    private void btnRptUsuarios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRptUsuarios3ActionPerformed
      reporteTotal menu = new reporteTotal();
        menu.setVisible(true);
        this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_btnRptUsuarios3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRptUsuarios;
    private javax.swing.JButton btnRptUsuarios1;
    private javax.swing.JButton btnRptUsuarios2;
    private javax.swing.JButton btnRptUsuarios3;
    private javax.swing.JPanel pnlUno;
    // End of variables declaration//GEN-END:variables
}
